from .product_view import IndexView,ProductView,ProductCreateView,ProductDeleteView,ProductUpdateView

from .review_views import ReviewIndexView,ReviewView,ReviewCreateView,ReviewDeleteView,ReviewUpdateView