# Generated by Django 2.2 on 2019-11-16 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('category', models.CharField(blank=True, choices=[('other', 'Другое'), ('cars', 'Машины'), ('books', 'Книги'), ('music', 'Музыка')], default='other', max_length=50, verbose_name='Категория')),
                ('description', models.CharField(blank=True, max_length=3000, verbose_name='описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000, verbose_name='описание')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_creator', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='webapp.Product', verbose_name='продукт')),
            ],
        ),
    ]
