# Generated by Django 2.2 on 2019-11-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191116_0609'),
    ]

    operations = [
    ]
